version: "3.7"

services:
  universities:
    container_name: universities
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "yarn start"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
