version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@8.2.1
  docker: circleci/docker@1.4.0

jobs:
  setup-project:
    docker:
      - image: node
      - image: circleci/mongo:4.4
        auth:
          # these env vars are setted in circleci configs
          # if you wanna implement CI/CD with circleci checkout the docummentation in https://circleci.com/docs/
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - run:
          name: MongoDB Install
          command: |
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "install depenpendencies"
          command: yarn install
      - run:
          name: "build project"
          command: yarn build
      - run:
          name: "running tests"
          command: yarn test

workflows:
  say-hello-workflow:
    jobs:
      - setup-project
